databases:
  - name: ayataka_DB
    databaseName: ayataka_db
    user: ayataka
    region: singapore

services:
  - type: web
    name: ayataka
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: ayataka_DB
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
